### ISSUE TITLE
Parsed Test results showing in its previous dependent workflow, rather than in its workflow

### ISSUE THREAD

**Issue by saiteja8848** [NasAmin/trx-parser#125]
I have 2 workflows  "DevBuild.yml"  and "RunTests.yml"(Both are dependent, executes one after other) . 
I am using TRX parser in "RunTests.yml", but it is showing showing parsed tests results report under "DevBuild.yml" and some times in "RunTest.yml" .

Fix it if it a bug 

Asked In Community as well
https://github.community/t/getting-job-results-of-workflow-2-in-workflow-1-how-to-fix-this/168499

**Comment by NasAmin** [comment]
@saiteja8848 Thanjs for the issue. I had encountered this before. Unfortunately this is a limitation in Github API.
I have documented some notes on #86

**Comment by saiteja8848** [comment]
Thanks a lot for responding. Hope will resolve this issue soon.


*Thanks & Regards*
*Saiteja Gurram.*
*Contact No:+91-7989027489*

**Comment by SaitejaGurram** [comment]
This isssue has not been resolved still, I don't see the parsed test results, I want passed test cases as well

**Comment by NasAmin** [comment]
@SaitejaGurram apologies.
The original issue cannot be solved as it is currently a limitation in Github API. Checkout the readme.

For the passing tests, feel free to create a new issue. I'd appreciate if you describe what value displaying passing tests will add on the new issue.
