### ISSUE TITLE
Support a 'sha' property to override which commit to associate with

### ISSUE THREAD

**Issue by flcdrg** [NasAmin/trx-parser#191]
If I wanted to use this action in a workflow triggered by `workflow_run` then the current sha defaults to main/master.

I'd like to be able to pass in github.event.workflow_run.head_sha instead (as that would be the sha from the original workflow who's completion caused the current workflow to run.

**Comment by NasAmin** [comment]
@flcdrg Thanks for contributing on #192. The PR has been merged and released as [v0.2.0](https://github.com/NasAmin/trx-parser/releases/tag/v0.2.0)

**Comment by NasAmin** [comment]
@flcdrg please let me know if this  issue can be closed.

**Comment by flcdrg** [comment]
Yes, all good!
