### ISSUE TITLE
The algorithm to generate report names does not generate unique names

### ISSUE THREAD

**Issue by lextm** [NasAmin/trx-parser#231]
Here is a repo that is being tested on multiple operating systems (`ubuntu-latest`, `macos-latest`, and `windows-latest`),

https://github.com/lextudio/sharpsnmplib/runs/4499386025?check_suite_focus=true

and you can see the reports from Ubuntu and macOS have the same name so in the end only one report is showed.

The algorithm should be improved such as adding the job name to report names.

**Comment by NasAmin** [comment]
@lextm Apologies for the massive delay. I have added a new optional `REPORT_PREFIX` input. This can be any string that you provide from your workflow.
