### ISSUE TITLE
Update to run using Node 20

### ISSUE THREAD

**Issue by SholomAber** [NasAmin/trx-parser#301]
Hi, are you planning to update this action to run on Node 20 per https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ ?

**Comment by NasAmin** [comment]
Sorry for the delayed response. A PR is welcome. Otherwise I'll try upgrading over the coming days.

**Comment by NasAmin** [comment]
This is now done. Release in [v0.6.0](https://github.com/NasAmin/trx-parser/releases/tag/v0.6.0)

**Comment by NasAmin** [comment]
I.ll close this issue for now. Please feel free to come back if you still see an issue.
