### ISSUE TITLE
Workflow not failing if there are test failures

### ISSUE THREAD

**Issue by bhojjoshi** [NasAmin/trx-parser#84]
trx-parser is not configurable for whether to break the workflow or proceed further in case of test failures, rather all the following steps/jobs get executed regardless of test status.

It would give more control to a developer if trx-parser can be configured based on some input parameters such as BREAK_ON_TEST_FAILURE with boolean values or similar.

**Comment by NasAmin** [comment]
For the time being there is a workaround as follows:
This actions produces an output call `test-outcome`. If there is at least one test failure, it will set this output to `Failed`.
You could then access this output of the action has run as a separate step in your pipeline.

I'll enhance this workflow with a new flag. The default will be the current behaviour but if the user sets the new flag then it will fail the task with exit code 1.

**Comment by bhojjoshi** [comment]
Yes, the workaround is working for me for now. Thanks!
